module VerifyExamples.Jsonstore.Dict0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Jsonstore exposing (..)
import Dict exposing (Dict)
import Json.Decode as D







spec0 : Test.Test
spec0 =
    Test.test "#dict: \n\n    \"{\\\"value\\\":42}\"\n    |> (int |> dict |> decode |> D.decodeString)\n    --> Ok (Dict.singleton \"value\" 42)" <|
        \() ->
            Expect.equal
                (
                "{\"value\":42}"
                |> (int |> dict |> decode |> D.decodeString)
                )
                (
                Ok (Dict.singleton "value" 42)
                )