module VerifyExamples.Jsonstore.Float0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Jsonstore exposing (..)
import Json.Decode as D







spec0 : Test.Test
spec0 =
    Test.test "#float: \n\n    \"3.14\" |> (float |> decode |> D.decodeString)\n    --> Ok 3.14" <|
        \() ->
            Expect.equal
                (
                "3.14" |> (float |> decode |> D.decodeString)
                )
                (
                Ok 3.14
                )