module VerifyExamples.Jsonstore.Int0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Jsonstore exposing (..)
import Json.Decode as D







spec0 : Test.Test
spec0 =
    Test.test "#int: \n\n    \"1\" |> (int |> decode |> D.decodeString)\n    --> Ok 1" <|
        \() ->
            Expect.equal
                (
                "1" |> (int |> decode |> D.decodeString)
                )
                (
                Ok 1
                )