module VerifyExamples.Jsonstore.Object0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Jsonstore exposing (..)
import Json.Decode as D

type alias Obj =
    { value : Int
    , name : String
    }





spec0 : Test.Test
spec0 =
    Test.test "#object: \n\n    \"{\\\"value\\\":42,\\\"name\\\":\\\"Elm\\\"}\"\n    |> ( object Obj\n        |> with \"value\" int .value\n        |> with \"name\" string .name\n        |> toJson\n        |> decode\n        |> D.decodeString\n        )\n    --> Ok {value=42,name=\"Elm\"}" <|
        \() ->
            Expect.equal
                (
                "{\"value\":42,\"name\":\"Elm\"}"
                |> ( object Obj
                    |> with "value" int .value
                    |> with "name" string .name
                    |> toJson
                    |> decode
                    |> D.decodeString
                    )
                )
                (
                Ok {value=42,name="Elm"}
                )