module VerifyExamples.Jsonstore.String0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Jsonstore exposing (..)
import Json.Decode as D







spec0 : Test.Test
spec0 =
    Test.test "#string: \n\n    \"\\\"Hello World\\\"\" |> (string |> decode |> D.decodeString)\n    --> Ok \"Hello World\"" <|
        \() ->
            Expect.equal
                (
                "\"Hello World\"" |> (string |> decode |> D.decodeString)
                )
                (
                Ok "Hello World"
                )